### ISSUE TITLE
On job summary page, stage group files are unordered

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/bespin-ui#108]
The jumbled order on the confirmation page before submitting a job causes confusion and prompted the user to check if the files would in fact be in the correct order.

<img width="482" alt="screen shot 2017-12-07 at 2 40 38 pm" src="https://user-images.githubusercontent.com/2752599/33735236-baccfd40-db5c-11e7-8670-a211f76216d9.png">

**Comment by dleehr** [comment]
These should be ordered in the way they were chosen

**Comment by johnbradley** [comment]
Seems like the default sort with Ember is random. Clicking refresh changes the order items list.
There doesn't appear to be any good fields to sort on provided by dds-job-input-files api.

The simplest possible change is to sort by id:
https://github.com/Duke-GCB/bespin-ui/blob/19db95db47cf26804074b202ee924d5bf1062204/app/components/job-file-stage-group-detail.js#L5-L7
This works due to the order we currently create the files (the order the user specifies).
This seems rather fragile.

Other ideas: 
- look through jobOrder and let that order the files. This could get pretty painful as we end up with different CWL data structures.
- add a sequence field to the dds-job-input-files API

**Comment by dleehr** [comment]
My initial thought was that we'd need to add a sequence field to the job input files objects, and that sequence field would be determined by the order chosen when creating the job
